CREATE DATABASE pharmacy_ms;

CREATE TABLE User
(
  U_Name VARCHAR(20) NOT NULL,
  U_ID INT NOT NULL,
  U_DOB DATE NOT NULL,
  U_Password VARCHAR(10) NOT NULL,
  U_Phone_no VARCHAR(12) NOT NULL,
  U_Address VARCHAR(50) NOT NULL,
  PRIMARY KEY (U_ID)
);

CREATE TABLE Distributor
(
  D_Name VARCHAR(15) NOT NULL,
  D_ID INT NOT NULL,
  D_Phone_no VARCHAR(12) NOT NULL,
  D_Address VARCHAR(50) NOT NULL,
  PRIMARY KEY (D_ID)
);

CREATE TABLE Drug
(
  Dr_Name VARCHAR(20) NOT NULL,
  Dr_ID VARCHAR(10) NOT NULL,
  Dr_DOM DATE NOT NULL,
  Dr_DOE DATE NOT NULL,
  Dr_MRP INT NOT NULL,
  Dr_Cost_Price INT NOT NULL,
  Dr_Type VARCHAR(20) NOT NULL,
  Dr_Use VARCHAR(15) NOT NULL,
  Dr_Quantity INT NOT NULL,
  D_ID INT NOT NULL,
  U_ID INT NOT NULL,
  PRIMARY KEY (Dr_ID),
  FOREIGN KEY (D_ID) REFERENCES Distributor(D_ID),
  FOREIGN KEY (U_ID) REFERENCES User(U_ID)
);

CREATE TABLE Customer
(
  C_Name VARCHAR(15) NOT NULL,
  C_ID VARCHAR(20) NOT NULL,
  C_Phone_no VARCHAR(12) NOT NULL,
  C_Gender VARCHAR(6) NOT NULL,
  PRIMARY KEY (C_ID)
);

CREATE TABLE Invoice
(
  I_Date DATE NOT NULL,
  I_Time VARCHAR(10) NOT NULL,
  I_Bill_Amount INT DEFAULT '1',
  I_No VARCHAR(10) NOT NULL,
  PRIMARY KEY (I_No)
);

CREATE TABLE buys_or_generates
(
  C_ID VARCHAR(20) NOT NULL,
  Dr_ID VARCHAR(10) NOT NULL,
  I_No VARCHAR(10) NOT NULL,
  Quantity INT NOT NULL,
  FOREIGN KEY (C_ID) REFERENCES Customer(C_ID),
  FOREIGN KEY (Dr_ID) REFERENCES Drug(Dr_ID),
  FOREIGN KEY (I_No) REFERENCES Invoice(I_No),
  PRIMARY KEY (C_ID,Dr_ID,I_No)
);

SHOW TABLES;

DESC buys_or_generates;

DESC customer;

DESC distributor;

DESC drug;

DESC invoice;

DESC user;
